
development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: punaise
  username: Hatchvenom
  password:
  allow_concurrency: true
  pool: 5
  min_messages: warning

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: punaise
  username: Hatchvenom
  password:
  allow_concurrency: true
  pool: 5
  min_messages: error


production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: punaise
  username: Hatchvenom
  password:
  allow_concurrency: true
  pool: 5
  min_messages: warning
